#!/bin/sh

set -e

# to disable precommit hook: "git config precommit.disable 1"
disable=`grep -Pzo '\[precommit\]\s+disable\s+=\s+1' .git/config &> /dev/null || false`
if [ "$disable" ]; then
  exit 0
fi

diff() {
  git diff-index --name-only HEAD
}

grepTypes() {
  diff | grep -Eq "\.($1)$"
  return $?
}

# run flow
if grepTypes "js|jsx"
then
  echo "=== Checking flow ..."
  npm run flow
fi

# run tests
if grepTypes "js"
then
  echo "\n=== Running tests..."
  npm run test
fi
