// flow-typed signature: 9117f30161ace958d6a0b928d7bd1c0c
// flow-typed version: <<STUB>>/@sepo27/redux-di_v1.0.0-alpha/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sepo27/redux-di'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sepo27/redux-di' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sepo27/redux-di/lib/combineReducers/combineReducers' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/combineReducers/functions/combineDiReducers' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/combineReducers/functions/resolveState' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/combineReducers/functions/utils' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/combineReducers/functions/validateCombineReducersParams' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/combineReducers/types' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/diReducer/diMemoReducer' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/diReducer/diReducer' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/diReducer/functions' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/diReducer/types' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/diSelector/DiSelector_DEPRECATED' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/diSelector/DiSelector' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/diSelector/types' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/index' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/initReducer/initReducer' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/types' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/utils/diPath' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/utils/isType' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/utils/objectShapeChecks' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/utils/objMap' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/utils/path' {
  declare module.exports: any;
}

declare module '@sepo27/redux-di/lib/utils/ReduxDiError' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sepo27/redux-di/lib/combineReducers/combineReducers.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/combineReducers/combineReducers'>;
}
declare module '@sepo27/redux-di/lib/combineReducers/functions/combineDiReducers.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/combineReducers/functions/combineDiReducers'>;
}
declare module '@sepo27/redux-di/lib/combineReducers/functions/resolveState.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/combineReducers/functions/resolveState'>;
}
declare module '@sepo27/redux-di/lib/combineReducers/functions/utils.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/combineReducers/functions/utils'>;
}
declare module '@sepo27/redux-di/lib/combineReducers/functions/validateCombineReducersParams.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/combineReducers/functions/validateCombineReducersParams'>;
}
declare module '@sepo27/redux-di/lib/combineReducers/types.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/combineReducers/types'>;
}
declare module '@sepo27/redux-di/lib/diReducer/diMemoReducer.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/diReducer/diMemoReducer'>;
}
declare module '@sepo27/redux-di/lib/diReducer/diReducer.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/diReducer/diReducer'>;
}
declare module '@sepo27/redux-di/lib/diReducer/functions.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/diReducer/functions'>;
}
declare module '@sepo27/redux-di/lib/diReducer/types.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/diReducer/types'>;
}
declare module '@sepo27/redux-di/lib/diSelector/DiSelector_DEPRECATED.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/diSelector/DiSelector_DEPRECATED'>;
}
declare module '@sepo27/redux-di/lib/diSelector/DiSelector.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/diSelector/DiSelector'>;
}
declare module '@sepo27/redux-di/lib/diSelector/types.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/diSelector/types'>;
}
declare module '@sepo27/redux-di/lib/index.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/index'>;
}
declare module '@sepo27/redux-di/lib/initReducer/initReducer.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/initReducer/initReducer'>;
}
declare module '@sepo27/redux-di/lib/types.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/types'>;
}
declare module '@sepo27/redux-di/lib/utils/diPath.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/utils/diPath'>;
}
declare module '@sepo27/redux-di/lib/utils/isType.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/utils/isType'>;
}
declare module '@sepo27/redux-di/lib/utils/objectShapeChecks.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/utils/objectShapeChecks'>;
}
declare module '@sepo27/redux-di/lib/utils/objMap.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/utils/objMap'>;
}
declare module '@sepo27/redux-di/lib/utils/path.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/utils/path'>;
}
declare module '@sepo27/redux-di/lib/utils/ReduxDiError.js' {
  declare module.exports: $Exports<'@sepo27/redux-di/lib/utils/ReduxDiError'>;
}
